#!/bin/sh

az storage blob upload-batch --account-name looperfrontend \
                              -d '$web'                    \
                              -s .                         \
                             --pattern '*.js'

az storage blob upload-batch --account-name looperfrontend \
                              -d '$web'                    \
                              -s .                         \
                             --pattern '*.html'

az storage blob upload-batch --account-name looperfrontend \
                              -d '$web'                    \
                              -s snd                       \
                             --destination-path snd        \
                             --pattern '*'
